// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace hGem.WebUI.Controllers
{
    public partial class DashboardControlsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DashboardControlsController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected DashboardControlsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DashboardControlsController Actions { get { return MVC.DashboardControls; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "DashboardControls";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "DashboardControls";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string TopNavigationBar = "TopNavigationBar";
            public readonly string SideNavigationBar = "SideNavigationBar";
            public readonly string TasksDropdown = "TasksDropdown";
            public readonly string NotificationsDropdown = "NotificationsDropdown";
            public readonly string MessagesDropdown = "MessagesDropdown";
            public readonly string UserDropdown = "UserDropdown";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string TopNavigationBar = "TopNavigationBar";
            public const string SideNavigationBar = "SideNavigationBar";
            public const string TasksDropdown = "TasksDropdown";
            public const string NotificationsDropdown = "NotificationsDropdown";
            public const string MessagesDropdown = "MessagesDropdown";
            public const string UserDropdown = "UserDropdown";
        }


        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string MessagesDropdown = "MessagesDropdown";
                public readonly string NotificationsDropdown = "NotificationsDropdown";
                public readonly string SideNavigationBar = "SideNavigationBar";
                public readonly string TasksDropdown = "TasksDropdown";
                public readonly string TopNavigationBar = "TopNavigationBar";
                public readonly string UserDropdown = "UserDropdown";
            }
            public readonly string MessagesDropdown = "~/Views/DashboardControls/MessagesDropdown.cshtml";
            public readonly string NotificationsDropdown = "~/Views/DashboardControls/NotificationsDropdown.cshtml";
            public readonly string SideNavigationBar = "~/Views/DashboardControls/SideNavigationBar.cshtml";
            public readonly string TasksDropdown = "~/Views/DashboardControls/TasksDropdown.cshtml";
            public readonly string TopNavigationBar = "~/Views/DashboardControls/TopNavigationBar.cshtml";
            public readonly string UserDropdown = "~/Views/DashboardControls/UserDropdown.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_DashboardControlsController : hGem.WebUI.Controllers.DashboardControlsController
    {
        public T4MVC_DashboardControlsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void TopNavigationBarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult TopNavigationBar()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TopNavigationBar);
            TopNavigationBarOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SideNavigationBarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SideNavigationBar()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SideNavigationBar);
            SideNavigationBarOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void TasksDropdownOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult TasksDropdown()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TasksDropdown);
            TasksDropdownOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NotificationsDropdownOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult NotificationsDropdown()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NotificationsDropdown);
            NotificationsDropdownOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MessagesDropdownOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult MessagesDropdown()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MessagesDropdown);
            MessagesDropdownOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UserDropdownOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult UserDropdown()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserDropdown);
            UserDropdownOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
