// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Warp.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ClientStatusEnum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClientStatusEnum));
        
        string IMigrationMetadata.Id
        {
            get { return "201412161058416_ClientStatusEnum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
