using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using Warp.Data.Entities;

namespace Warp.Data.Context
{
    /// <summary>
    /// EF's Unit of Work pattern.
    /// </summary>
    public interface IHospitalityGemDbContext
    {
        int SaveChanges();

        // Hooks into the DbContext.
        Database Database { get; }
        DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;

        IDbSet<AuditingDatabase> AuditingDatabases { get; set; }

        IDbSet<PasswordQuestion> PasswordQuestions { get; set; }
        IDbSet<PasswordReset> PasswordResets { get; set; }
        IDbSet<Permission> Permissions { get; set; }
        IDbSet<PermissionGroup> PermissionGroups { get; set; }
        IDbSet<PermissionGroupPermission> PermissionGroupPermissions { get; set; }
        IDbSet<PermissionGroupUser> PermissionGroupUsers { get; set; }
        IDbSet<Role> Roles { get; set; }
        IDbSet<User> Users { get; set; }
        IDbSet<UserImpersonationUserRole> UserImpersonationUserRoles { get; set; }
        IDbSet<UserRole> UserRoles { get; set; }
        IDbSet<AuditAction> AuditActions { get; set; }
        IDbSet<Event> Events { get; set; }
        IDbSet<EventCategory> EventCategories { get; set; }
        IDbSet<Operation> Operations { get; set; }
        IDbSet<Severity> Severities { get; set; }
        IDbSet<Area> Areas { get; set; }
        IDbSet<AreaHistory> AreaHistories { get; set; }
        IDbSet<AreaStatu> AreaStatus { get; set; }
        IDbSet<Branch> Branches { get; set; }
        IDbSet<BranchHistory> BranchHistories { get; set; }
        IDbSet<BranchLogo> BranchLogoes { get; set; }
        IDbSet<BranchStatu> BranchStatus { get; set; }
        IDbSet<Brand> Brands { get; set; }
        IDbSet<BrandHistory> BrandHistories { get; set; }
        IDbSet<BrandLogo> BrandLogoes { get; set; }
        IDbSet<BrandStatu> BrandStatus { get; set; }
        IDbSet<Client> Clients { get; set; }
        IDbSet<ClientAccountManager> ClientAccountManagers { get; set; }
        IDbSet<ClientContactStatu> ClientContactStatus { get; set; }
        IDbSet<ClientHistory> ClientHistories { get; set; }
        IDbSet<ClientLogo> ClientLogoes { get; set; }
        IDbSet<ClientOrganisation> ClientOrganisations { get; set; }
        IDbSet<ClientStatu> ClientStatus { get; set; }
        IDbSet<ContactAddressBranch> ContactAddressBranches { get; set; }
        IDbSet<ContactAddressBrand> ContactAddressBrands { get; set; }
        IDbSet<ContactAddressClient> ContactAddressClients { get; set; }
        IDbSet<ContactAddressUserRole> ContactAddressUserRoles { get; set; }
        IDbSet<Currency> Currencies { get; set; }
        IDbSet<IndustrySector> IndustrySectors { get; set; }
        IDbSet<Location> Locations { get; set; }
        IDbSet<LocationStatu> LocationStatus { get; set; }
        IDbSet<Logo> Logoes { get; set; }
        IDbSet<PermissionType> PermissionTypes { get; set; }
        IDbSet<Person> People { get; set; }
        IDbSet<PersonArea> PersonAreas { get; set; }
        IDbSet<PersonBranch> PersonBranches { get; set; }
        IDbSet<PersonBrand> PersonBrands { get; set; }
        IDbSet<PersonClient> PersonClients { get; set; }
        IDbSet<PersonRegion> PersonRegions { get; set; }
        IDbSet<PersonStatu> PersonStatus { get; set; }
        IDbSet<Region> Regions { get; set; }
        IDbSet<RegionGroup> RegionGroups { get; set; }
        IDbSet<RegionHistory> RegionHistories { get; set; }
        IDbSet<RegionStatu> RegionStatus { get; set; }
        IDbSet<AbsenceInstance> AbsenceInstances { get; set; }
        IDbSet<AbsenceType> AbsenceTypes { get; set; }
        IDbSet<AccountingClient> AccountingClients { get; set; }
        IDbSet<AccountingInvoice> AccountingInvoices { get; set; }
        IDbSet<AccountingPeriod> AccountingPeriods { get; set; }
        IDbSet<AccountingProduct> AccountingProducts { get; set; }
        IDbSet<AccountingTransaction> AccountingTransactions { get; set; }
        IDbSet<Action> Actions { get; set; }
        IDbSet<ActionComment> ActionComments { get; set; }
        IDbSet<ActionPriority> ActionPriorities { get; set; }
        IDbSet<ActionStatu> ActionStatus { get; set; }
        IDbSet<ActionType> ActionTypes { get; set; }
        IDbSet<ActionUser> ActionUsers { get; set; }
        IDbSet<AdminClientContactTracking> AdminClientContactTrackings { get; set; }
        IDbSet<Airport> Airports { get; set; }
        IDbSet<AreaQuestionnaire> AreaQuestionnaires { get; set; }
        IDbSet<Assessment> Assessments { get; set; }
        IDbSet<AssessmentArea> AssessmentAreas { get; set; }
        IDbSet<AssessmentAreaBranch> AssessmentAreaBranches { get; set; }
        IDbSet<AssessmentType> AssessmentTypes { get; set; }
        IDbSet<Assessor> Assessors { get; set; }
        IDbSet<AssessorAttribute> AssessorAttributes { get; set; }
        IDbSet<AssessorAttributeItem> AssessorAttributeItems { get; set; }
        IDbSet<AssessorAttributeOption> AssessorAttributeOptions { get; set; }
        IDbSet<AssessorCallBackRequest> AssessorCallBackRequests { get; set; }
        IDbSet<AssessorCallInLog> AssessorCallInLogs { get; set; }
        IDbSet<AssessorExpense> AssessorExpenses { get; set; }
        IDbSet<AssessorExpenseHistory> AssessorExpenseHistories { get; set; }
        IDbSet<AssessorGeographicPostCode> AssessorGeographicPostCodes { get; set; }
        IDbSet<AssessorHistory> AssessorHistories { get; set; }
        IDbSet<AssessorLevel> AssessorLevels { get; set; }
        IDbSet<AssessorNote> AssessorNotes { get; set; }
        IDbSet<AssessorStatu> AssessorStatus { get; set; }
        IDbSet<AssessorStatusChangeReason> AssessorStatusChangeReasons { get; set; }
        IDbSet<AssessorTimeTracker> AssessorTimeTrackers { get; set; }
        IDbSet<AuditAdminEvent> AuditAdminEvents { get; set; }
        IDbSet<AuditAssessorEvent> AuditAssessorEvents { get; set; }
        IDbSet<AuditPersonEvent> AuditPersonEvents { get; set; }
        IDbSet<AuditTable> AuditTables { get; set; }
        IDbSet<BanBranch> BanBranches { get; set; }
        IDbSet<BanBrand> BanBrands { get; set; }
        IDbSet<BanClient> BanClients { get; set; }
        IDbSet<Benchmark> Benchmarks { get; set; }
        IDbSet<BranchAccountingProduct> BranchAccountingProducts { get; set; }
        IDbSet<BranchNote> BranchNotes { get; set; }
        IDbSet<BranchQuestionnaire> BranchQuestionnaires { get; set; }
        IDbSet<BrandAccountingProduct> BrandAccountingProducts { get; set; }
        IDbSet<BrandNote> BrandNotes { get; set; }
        IDbSet<BrandQuestionnaire> BrandQuestionnaires { get; set; }
        IDbSet<Brief> Briefs { get; set; }
        IDbSet<BriefBranch> BriefBranches { get; set; }
        IDbSet<BriefBrand> BriefBrands { get; set; }
        IDbSet<BriefClient> BriefClients { get; set; }
        IDbSet<BriefConfiguration> BriefConfigurations { get; set; }
        IDbSet<BriefConfigurationBranch> BriefConfigurationBranches { get; set; }
        IDbSet<BriefConfigurationBrand> BriefConfigurationBrands { get; set; }
        IDbSet<BriefItem> BriefItems { get; set; }
        IDbSet<BriefSection> BriefSections { get; set; }
        IDbSet<BroadcastMessage> BroadcastMessages { get; set; }
        IDbSet<BroadcastMessageUser> BroadcastMessageUsers { get; set; }
        IDbSet<CallBackRequest> CallBackRequests { get; set; }
        IDbSet<CallInLog> CallInLogs { get; set; }
        IDbSet<CCTFurtherNote> CCTFurtherNotes { get; set; }
        IDbSet<ClientAccountingProduct> ClientAccountingProducts { get; set; }
        IDbSet<ClientCallBackRequest> ClientCallBackRequests { get; set; }
        IDbSet<ClientCallInLog> ClientCallInLogs { get; set; }
        IDbSet<ClientCommunicationLog> ClientCommunicationLogs { get; set; }
        IDbSet<ClientContactTracking> ClientContactTrackings { get; set; }
        IDbSet<ClientNote> ClientNotes { get; set; }
        IDbSet<ClientQuestionnaire> ClientQuestionnaires { get; set; }
        IDbSet<CommunicationPreference> CommunicationPreferences { get; set; }
        IDbSet<CommunicationStatu> CommunicationStatus { get; set; }
        IDbSet<CommunicationType> CommunicationTypes { get; set; }
        IDbSet<Configuration> Configurations { get; set; }
        IDbSet<ConfigurationItem> ConfigurationItems { get; set; }
        IDbSet<ConfigurationSystem> ConfigurationSystems { get; set; }
        IDbSet<ConfigurationType> ConfigurationTypes { get; set; }
        IDbSet<ContactAddressCustomer> ContactAddressCustomers { get; set; }
        IDbSet<CriteriaAssessorAttribute> CriteriaAssessorAttributes { get; set; }
        IDbSet<CriteriaConfig> CriteriaConfigs { get; set; }
        IDbSet<CriteriaOperator> CriteriaOperators { get; set; }
        IDbSet<CriteriaOption> CriteriaOptions { get; set; }
        IDbSet<CriteriaSet> CriteriaSets { get; set; }
        IDbSet<CurrencyExchangeRate> CurrencyExchangeRates { get; set; }
        IDbSet<Customer> Customers { get; set; }
        IDbSet<CustomerClient> CustomerClients { get; set; }
        IDbSet<CustomerLinkStatu> CustomerLinkStatus { get; set; }
        IDbSet<CustomerUser> CustomerUsers { get; set; }
        IDbSet<DynamicQuestion> DynamicQuestions { get; set; }
        IDbSet<Error> Errors { get; set; }
        IDbSet<ExpenseStatu> ExpenseStatus { get; set; }
        IDbSet<ExpenseType> ExpenseTypes { get; set; }
        IDbSet<ForumAdminReply> ForumAdminReplies { get; set; }
        IDbSet<ForumAssessorReply> ForumAssessorReplies { get; set; }
        IDbSet<ForumCategory> ForumCategories { get; set; }
        IDbSet<ForumReportedReply> ForumReportedReplies { get; set; }
        IDbSet<ForumThread> ForumThreads { get; set; }
        IDbSet<FurtherActionComment> FurtherActionComments { get; set; }
        IDbSet<FurtherNote> FurtherNotes { get; set; }
        IDbSet<Gender> Genders { get; set; }
        IDbSet<Group> Groups { get; set; }
        IDbSet<GroupUser> GroupUsers { get; set; }
        IDbSet<Log> Logs { get; set; }
        IDbSet<Login> Logins { get; set; }
        IDbSet<Maintenance> Maintenances { get; set; }
        IDbSet<MaintenanceCategory> MaintenanceCategories { get; set; }
        IDbSet<MaintenanceCustomer> MaintenanceCustomers { get; set; }
        IDbSet<ManagementCategory> ManagementCategories { get; set; }
        IDbSet<Menu> Menus { get; set; }
        IDbSet<MenuConfig> MenuConfigs { get; set; }
        IDbSet<MenuConfigBranch> MenuConfigBranches { get; set; }
        IDbSet<MenuConfigBrand> MenuConfigBrands { get; set; }
        IDbSet<MenuConfigClient> MenuConfigClients { get; set; }
        IDbSet<MenuItem> MenuItems { get; set; }
        IDbSet<MenuItemPossibleAnswer> MenuItemPossibleAnswers { get; set; }
        IDbSet<MenuSection> MenuSections { get; set; }
        IDbSet<MenuSectionPossibleAnswer> MenuSectionPossibleAnswers { get; set; }
        IDbSet<Note> Notes { get; set; }
        IDbSet<NoteCalendar> NoteCalendars { get; set; }
        IDbSet<NoteType> NoteTypes { get; set; }
        IDbSet<Notification> Notifications { get; set; }
        IDbSet<NotificationCategory> NotificationCategories { get; set; }
        IDbSet<PandoraCache> PandoraCaches { get; set; }
        IDbSet<Period> Periods { get; set; }
        IDbSet<PeriodBrand> PeriodBrands { get; set; }
        IDbSet<PeriodClient> PeriodClients { get; set; }
        IDbSet<PersonCallBackRequest> PersonCallBackRequests { get; set; }
        IDbSet<PersonClientContactTracking> PersonClientContactTrackings { get; set; }
        IDbSet<PersonTimeTracker> PersonTimeTrackers { get; set; }
        IDbSet<Point> Points { get; set; }
        IDbSet<PointReason> PointReasons { get; set; }
        IDbSet<PossibleAnswer> PossibleAnswers { get; set; }
        IDbSet<Question> Questions { get; set; }
        IDbSet<QuestionDepartment> QuestionDepartments { get; set; }
        IDbSet<Questionnaire> Questionnaires { get; set; }
        IDbSet<QuestionnaireAccountingProduct> QuestionnaireAccountingProducts { get; set; }
        IDbSet<QuestionnaireQuestion> QuestionnaireQuestions { get; set; }
        IDbSet<QuestionnaireQuestionPossibleAnswer> QuestionnaireQuestionPossibleAnswers { get; set; }
        IDbSet<QuestionnaireStatu> QuestionnaireStatus { get; set; }
        IDbSet<QuestionOverwrite> QuestionOverwrites { get; set; }
        IDbSet<QuestionPossibleAnswer> QuestionPossibleAnswers { get; set; }
        IDbSet<QuestionResult> QuestionResults { get; set; }
        IDbSet<QuestionResultAction> QuestionResultActions { get; set; }
        IDbSet<QuestionSection> QuestionSections { get; set; }
        IDbSet<QuestionTag> QuestionTags { get; set; }
        IDbSet<QuestionTracker> QuestionTrackers { get; set; }
        IDbSet<QuestionType> QuestionTypes { get; set; }
        IDbSet<RailStation> RailStations { get; set; }
        IDbSet<RegionQuestionnaire> RegionQuestionnaires { get; set; }
        IDbSet<RemovalReason> RemovalReasons { get; set; }
        IDbSet<ReportProblemAction> ReportProblemActions { get; set; }
        IDbSet<ReportProblemActionType> ReportProblemActionTypes { get; set; }
        IDbSet<ReportProblemCause> ReportProblemCauses { get; set; }
        IDbSet<ReportProblemTracking> ReportProblemTrackings { get; set; }
        IDbSet<ReportProblemTrackingAction> ReportProblemTrackingActions { get; set; }
        IDbSet<ReportProblemType> ReportProblemTypes { get; set; }
        IDbSet<ResultComment> ResultComments { get; set; }
        IDbSet<SimpleVisit> SimpleVisits { get; set; }
        IDbSet<SimpleVisitQuestionResult> SimpleVisitQuestionResults { get; set; }
        IDbSet<SimpleVisitTemplate> SimpleVisitTemplates { get; set; }
        IDbSet<SimpleVisitTemplateBranch> SimpleVisitTemplateBranches { get; set; }
        IDbSet<SQQOPossibleAnswer> SQQOPossibleAnswers { get; set; }
        IDbSet<StaffAge> StaffAges { get; set; }
        IDbSet<StaffClothingColour> StaffClothingColours { get; set; }
        IDbSet<StaffClothingItem> StaffClothingItems { get; set; }
        IDbSet<StaffFeature> StaffFeatures { get; set; }
        IDbSet<StaffHairColour> StaffHairColours { get; set; }
        IDbSet<StaffHairLength> StaffHairLengths { get; set; }
        IDbSet<StaffHairStyle> StaffHairStyles { get; set; }
        IDbSet<StaffHeight> StaffHeights { get; set; }
        IDbSet<StaffMember> StaffMembers { get; set; }
        IDbSet<StaffMemberClothingItem> StaffMemberClothingItems { get; set; }
        IDbSet<StaffMemberFeature> StaffMemberFeatures { get; set; }
        IDbSet<SubDynamicQuestion> SubDynamicQuestions { get; set; }
        IDbSet<SubQuestionnaire> SubQuestionnaires { get; set; }
        IDbSet<SubQuestionnaireQuestionOverwrite> SubQuestionnaireQuestionOverwrites { get; set; }
        IDbSet<Suggestion> Suggestions { get; set; }
        IDbSet<SuggestionStatu> SuggestionStatus { get; set; }
        IDbSet<SuggestionVote> SuggestionVotes { get; set; }
        IDbSet<sysdiagram> sysdiagrams { get; set; }
        IDbSet<Tag> Tags { get; set; }
        IDbSet<TelephoneRecording> TelephoneRecordings { get; set; }
        IDbSet<Terminology> Terminologies { get; set; }
        IDbSet<TerminologyBrand> TerminologyBrands { get; set; }
        IDbSet<TerminologyClient> TerminologyClients { get; set; }
        IDbSet<TimeTracker> TimeTrackers { get; set; }
        IDbSet<TimeTrackerType> TimeTrackerTypes { get; set; }
        IDbSet<TradeLevel> TradeLevels { get; set; }
        IDbSet<Visit> Visits { get; set; }
        IDbSet<VisitAction> VisitActions { get; set; }
        IDbSet<VisitAssessor> VisitAssessors { get; set; }
        IDbSet<VisitCallBackRequest> VisitCallBackRequests { get; set; }
        IDbSet<VisitCallInLog> VisitCallInLogs { get; set; }
        IDbSet<VisitDetail> VisitDetails { get; set; }
        IDbSet<VisitNote> VisitNotes { get; set; }
        IDbSet<VisitPoint> VisitPoints { get; set; }
        IDbSet<VisitStatu> VisitStatus { get; set; }
        IDbSet<VisitStatusHistory> VisitStatusHistories { get; set; }
        IDbSet<VisitTimeTracker> VisitTimeTrackers { get; set; }
        IDbSet<VisitType> VisitTypes { get; set; }
        IDbSet<VisitTypeExpenseType> VisitTypeExpenseTypes { get; set; }
        IDbSet<Weather> Weathers { get; set; }
        IDbSet<ContactAddress> ContactAddresses { get; set; }
        IDbSet<ContactAddressGeoLocation> ContactAddressGeoLocations { get; set; }
        IDbSet<ContactAddressType> ContactAddressTypes { get; set; }
        IDbSet<GeographicCountry> GeographicCountries { get; set; }
        IDbSet<GeographicCounty> GeographicCounties { get; set; }
        IDbSet<GeographicLocation> GeographicLocations { get; set; }
        IDbSet<GeographicPostalArea> GeographicPostalAreas { get; set; }
        IDbSet<GeographicPostCode> GeographicPostCodes { get; set; }
        IDbSet<GeographicRegion> GeographicRegions { get; set; }
        IDbSet<GeographicWorldArea> GeographicWorldAreas { get; set; }
        IDbSet<Article> Articles { get; set; }
        IDbSet<ArticlePermission> ArticlePermissions { get; set; }
        IDbSet<Page> Pages { get; set; }
        IDbSet<PageArticle> PageArticles { get; set; }
        IDbSet<PageTour> PageTours { get; set; }
        IDbSet<Tour> Tours { get; set; }
        IDbSet<TourStep> TourSteps { get; set; }
        IDbSet<TourStepPlacement> TourStepPlacements { get; set; }
        IDbSet<TourUserRole> TourUserRoles { get; set; }
        IDbSet<TourUserRoleTourStep> TourUserRoleTourSteps { get; set; }
        IDbSet<AreaLegacyUser> AreaLegacyUsers { get; set; }
        IDbSet<BranchLegacyUser> BranchLegacyUsers { get; set; }
        IDbSet<BrandLegacyUser> BrandLegacyUsers { get; set; }
        IDbSet<ClientLegacyUser> ClientLegacyUsers { get; set; }
        IDbSet<RegionLegacyUser> RegionLegacyUsers { get; set; }
        IDbSet<Report> Reports { get; set; }
        IDbSet<ReportCategory> ReportCategories { get; set; }
        IDbSet<ReportParameterType> ReportParameterTypes { get; set; }
        IDbSet<ReportParameterValue> ReportParameterValues { get; set; }
        IDbSet<ReportReportType> ReportReportTypes { get; set; }
        IDbSet<ReportRestrictionClient> ReportRestrictionClients { get; set; }
        IDbSet<ReportSection> ReportSections { get; set; }
        IDbSet<ReportSource> ReportSources { get; set; }
        IDbSet<ReportType> ReportTypes { get; set; }
        IDbSet<Messages_0> Messages_0 { get; set; }
        IDbSet<Messages_0_Id> Messages_0_Id { get; set; }
        IDbSet<Schema> Schemata { get; set; }
        IDbSet<BranchSocialNetwork> BranchSocialNetworks { get; set; }
        IDbSet<BrandSocialNetwork> BrandSocialNetworks { get; set; }
        IDbSet<ClientSocialNetwork> ClientSocialNetworks { get; set; }
        IDbSet<SocialNetwork> SocialNetworks { get; set; }
        IDbSet<CustomCalendar> CustomCalendars { get; set; }
        IDbSet<CustomCalendarDate> CustomCalendarDates { get; set; }
        IDbSet<DayOfWeek> DayOfWeeks { get; set; }
        IDbSet<DelayType> DelayTypes { get; set; }
        IDbSet<Destination> Destinations { get; set; }
        IDbSet<DestinationEmail> DestinationEmails { get; set; }
        IDbSet<DestinationFileShare> DestinationFileShares { get; set; }
        IDbSet<DestinationFTP> DestinationFTPs { get; set; }
        IDbSet<DestinationType> DestinationTypes { get; set; }
        IDbSet<DynamicText> DynamicTexts { get; set; }
        IDbSet<EmailRecipient> EmailRecipients { get; set; }
        IDbSet<Month> Months { get; set; }
        IDbSet<ParameterOption> ParameterOptions { get; set; }
        IDbSet<Quarter> Quarters { get; set; }
        IDbSet<ReportFormat> ReportFormats { get; set; }
        IDbSet<Schedule> Schedules { get; set; }
        IDbSet<ScheduleCustomCalendar> ScheduleCustomCalendars { get; set; }
        IDbSet<ScheduleDaily> ScheduleDailies { get; set; }
        IDbSet<ScheduleMonthly> ScheduleMonthlies { get; set; }
        IDbSet<ScheduleMonthlyMonth> ScheduleMonthlyMonths { get; set; }
        IDbSet<ScheduleQuarterly> ScheduleQuarterlies { get; set; }
        IDbSet<ScheduleQuarterlyQuarter> ScheduleQuarterlyQuarters { get; set; }
        IDbSet<ScheduleSpecific> ScheduleSpecifics { get; set; }
        IDbSet<ScheduleSubType> ScheduleSubTypes { get; set; }
        IDbSet<ScheduleType> ScheduleTypes { get; set; }
        IDbSet<ScheduleWeekly> ScheduleWeeklies { get; set; }
        IDbSet<ScheduleWeeklyDayOfWeek> ScheduleWeeklyDayOfWeeks { get; set; }
        IDbSet<ScheduleYearly> ScheduleYearlies { get; set; }
        IDbSet<Subscription> Subscriptions { get; set; }
        IDbSet<SubscriptionDestination> SubscriptionDestinations { get; set; }
        IDbSet<SubscriptionDocument> SubscriptionDocuments { get; set; }
        IDbSet<SubscriptionEvent> SubscriptionEvents { get; set; }
        IDbSet<SubscriptionEventType> SubscriptionEventTypes { get; set; }
        IDbSet<SubscriptionReport> SubscriptionReports { get; set; }
        IDbSet<SubscriptionReportDestination> SubscriptionReportDestinations { get; set; }
        IDbSet<SubscriptionReportParameter> SubscriptionReportParameters { get; set; }
        IDbSet<SubscriptionStatu> SubscriptionStatus { get; set; }
        IDbSet<SubscriptionStatusType> SubscriptionStatusTypes { get; set; }
        IDbSet<Trigger> Triggers { get; set; }
        IDbSet<TriggerCheck> TriggerChecks { get; set; }
        IDbSet<TriggerEvent> TriggerEvents { get; set; }
        IDbSet<TriggerHistory> TriggerHistories { get; set; }
        IDbSet<TriggerInstance> TriggerInstances { get; set; }
        IDbSet<TriggerInstanceReport> TriggerInstanceReports { get; set; }
        IDbSet<TriggerInstanceReportStatusType> TriggerInstanceReportStatusTypes { get; set; }
        IDbSet<ApplicationLanguage> ApplicationLanguages { get; set; }
        IDbSet<CodeResource> CodeResources { get; set; }
        IDbSet<CodeResourceType> CodeResourceTypes { get; set; }
        IDbSet<Translation> Translations { get; set; }
    }
}