using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using Warp.Data.Models;

namespace Warp.Data
{
    /// <summary>
    /// EF's Unit of Work pattern.
    /// </summary>
    public interface IHospitalityGemDbContext
    {
        int SaveChanges();
        
        // Hooks into the DbContext.
        Database Database { get; }
        DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;

        IDbSet<ActionCategory> ActionCategories { get; set; }
        IDbSet<ActionEvent> ActionEvents { get; set; }
        IDbSet<Event> Events { get; set; }
        IDbSet<Operation> Operations { get; set; }
        IDbSet<Severity> Severities { get; set; }
        IDbSet<Area> Areas { get; set; }
        IDbSet<AreaHistory> AreaHistories { get; set; }
        IDbSet<AreaStatu> AreaStatus { get; set; }
        IDbSet<Branch> Branches { get; set; }
        IDbSet<BranchHistory> BranchHistories { get; set; }
        IDbSet<BranchLogo> BranchLogos { get; set; }
        IDbSet<Logo> Logos { get; set; }
        IDbSet<BranchStatu> BranchStatus { get; set; }
        IDbSet<Brand> Brands { get; set; }
        IDbSet<BrandHistory> BrandHistories { get; set; }
        IDbSet<BrandStatu> BrandStatus { get; set; }
        IDbSet<Client> Clients { get; set; }
        IDbSet<ClientAccountManager> ClientAccountManagers { get; set; }
        IDbSet<ClientContactStatu> ClientContactStatus { get; set; }
        IDbSet<ClientLogo> ClientLogos { get; set; }
        IDbSet<ClientStatu> ClientStatus { get; set; }
        IDbSet<ContactAddressBranch> ContactAddressBranches { get; set; }
        IDbSet<ContactAddressBrand> ContactAddressBrands { get; set; }
        IDbSet<ContactAddressGeoLocation> ContactAddressGeoLocations { get; set; }
        IDbSet<Location> Locations { get; set; }
        IDbSet<LocationStatu> LocationStatus { get; set; }
        IDbSet<Person> People { get; set; }
        IDbSet<PersonStatu> PersonStatus { get; set; }
        IDbSet<Region> Regions { get; set; }
        IDbSet<RegionGroup> RegionGroups { get; set; }
        IDbSet<RegionHistory> RegionHistories { get; set; }
        IDbSet<RegionStatu> RegionStatus { get; set; }
        IDbSet<AbsenceInstance> AbsenceInstances { get; set; }
        IDbSet<AbsenceType> AbsenceTypes { get; set; }
        IDbSet<AccountingClient> AccountingClients { get; set; }
        IDbSet<AccountingInvoice> AccountingInvoices { get; set; }
        IDbSet<AccountingPeriod> AccountingPeriods { get; set; }
        IDbSet<AccountingProduct> AccountingProducts { get; set; }
        IDbSet<AccountingTransaction> AccountingTransactions { get; set; }
        IDbSet<ActionComment> ActionComments { get; set; }
        IDbSet<ActionPriority> ActionPriorities { get; set; }
        IDbSet<ActionStatu> ActionStatus { get; set; }
        IDbSet<ActionType> ActionTypes { get; set; }
        IDbSet<ActionUser> ActionUsers { get; set; }
        IDbSet<AdminClientContactTracking> AdminClientContactTrackings { get; set; }
        IDbSet<Airport> Airports { get; set; }
        IDbSet<ApplicationLanguage> ApplicationLanguages { get; set; }
        IDbSet<Area1> Area1 { get; set; }
        IDbSet<AreaHistory1> AreaHistory1 { get; set; }
        IDbSet<AreaQuestionnaire> AreaQuestionnaires { get; set; }
        IDbSet<AreaStatus1> AreaStatus1 { get; set; }
        IDbSet<Assessment> Assessments { get; set; }
        IDbSet<AssessmentArea> AssessmentAreas { get; set; }
        IDbSet<AssessmentAreaBranch> AssessmentAreaBranches { get; set; }
        IDbSet<AssessmentType> AssessmentTypes { get; set; }
        IDbSet<Assessor> Assessors { get; set; }
        IDbSet<AssessorAttribute> AssessorAttributes { get; set; }
        IDbSet<AssessorAttributeItem> AssessorAttributeItems { get; set; }
        IDbSet<AssessorAttributeOption> AssessorAttributeOptions { get; set; }
        IDbSet<AssessorCallBackRequest> AssessorCallBackRequests { get; set; }
        IDbSet<AssessorCallInLog> AssessorCallInLogs { get; set; }
        IDbSet<AssessorExpense> AssessorExpenses { get; set; }
        IDbSet<AssessorExpenseHistory> AssessorExpenseHistories { get; set; }
        IDbSet<AssessorGeographicPostCode> AssessorGeographicPostCodes { get; set; }
        IDbSet<AssessorHistory> AssessorHistories { get; set; }
        IDbSet<AssessorLevel> AssessorLevels { get; set; }
        IDbSet<AssessorNote> AssessorNotes { get; set; }
        IDbSet<AssessorStatu> AssessorStatus { get; set; }
        IDbSet<AssessorStatusChangeReason> AssessorStatusChangeReasons { get; set; }
        IDbSet<AssessorTimeTracker> AssessorTimeTrackers { get; set; }
        IDbSet<AuditAction> AuditActions { get; set; }
        IDbSet<AuditAdminEvent> AuditAdminEvents { get; set; }
        IDbSet<AuditAssessorEvent> AuditAssessorEvents { get; set; }
        IDbSet<AuditManagerEvent> AuditManagerEvents { get; set; }
        IDbSet<AuditPersonEvent> AuditPersonEvents { get; set; }
        IDbSet<AuditTable> AuditTables { get; set; }
        IDbSet<BanBranch> BanBranches { get; set; }
        IDbSet<BanBrand> BanBrands { get; set; }
        IDbSet<BanClient> BanClients { get; set; }
        IDbSet<Benchmark> Benchmarks { get; set; }
        IDbSet<Branch1> Branch1 { get; set; }
        IDbSet<BranchAccountingProduct> BranchAccountingProducts { get; set; }
        IDbSet<BranchHistory1> BranchHistory1 { get; set; }
        IDbSet<BranchNote> BranchNotes { get; set; }
        IDbSet<BranchQuestionnaire> BranchQuestionnaires { get; set; }
        IDbSet<BranchStatus1> BranchStatus1 { get; set; }
        IDbSet<Brand1> Brand1 { get; set; }
        IDbSet<BrandAccountingProduct> BrandAccountingProducts { get; set; }
        IDbSet<BrandHistory1> BrandHistory1 { get; set; }
        IDbSet<BrandNote> BrandNotes { get; set; }
        IDbSet<BrandQuestionnaire> BrandQuestionnaires { get; set; }
        IDbSet<BrandStatus1> BrandStatus1 { get; set; }
        IDbSet<Brief> Briefs { get; set; }
        IDbSet<BriefBranch> BriefBranches { get; set; }
        IDbSet<BriefBrand> BriefBrands { get; set; }
        IDbSet<BriefClient> BriefClients { get; set; }
        IDbSet<BriefConfiguration> BriefConfigurations { get; set; }
        IDbSet<BriefConfigurationBranch> BriefConfigurationBranches { get; set; }
        IDbSet<BriefConfigurationBrand> BriefConfigurationBrands { get; set; }
        IDbSet<BriefItem> BriefItems { get; set; }
        IDbSet<BriefSection> BriefSections { get; set; }
        IDbSet<BroadcastMessage> BroadcastMessages { get; set; }
        IDbSet<BroadcastMessageUser> BroadcastMessageUsers { get; set; }
        IDbSet<CallBackRequest> CallBackRequests { get; set; }
        IDbSet<CallInLog> CallInLogs { get; set; }
        IDbSet<CCTFurtherNote> CCTFurtherNotes { get; set; }
        IDbSet<Client1> Client1 { get; set; }
        IDbSet<ClientAccountingProduct> ClientAccountingProducts { get; set; }
        IDbSet<ClientCallBackRequest> ClientCallBackRequests { get; set; }
        IDbSet<ClientCallInLog> ClientCallInLogs { get; set; }
        IDbSet<ClientCommunicationLog> ClientCommunicationLogs { get; set; }
        IDbSet<ClientContactStatus1> ClientContactStatus1 { get; set; }
        IDbSet<ClientContactTracking> ClientContactTrackings { get; set; }
        IDbSet<ClientHistory> ClientHistories { get; set; }
        IDbSet<ClientNote> ClientNotes { get; set; }
        IDbSet<ClientQuestionnaire> ClientQuestionnaires { get; set; }
        IDbSet<ClientStatus1> ClientStatus1 { get; set; }
        IDbSet<CommunicationPreference> CommunicationPreferences { get; set; }
        IDbSet<CommunicationStatu> CommunicationStatus { get; set; }
        IDbSet<CommunicationType> CommunicationTypes { get; set; }
        IDbSet<Configuration> Configurations { get; set; }
        IDbSet<ConfigurationItem> ConfigurationItems { get; set; }
        IDbSet<ConfigurationSystem> ConfigurationSystems { get; set; }
        IDbSet<ConfigurationType> ConfigurationTypes { get; set; }
        IDbSet<ContactAddress> ContactAddresses { get; set; }
        IDbSet<ContactAddressBranch1> ContactAddressBranch1 { get; set; }
        IDbSet<ContactAddressBrand1> ContactAddressBrand1 { get; set; }
        IDbSet<ContactAddressClient> ContactAddressClients { get; set; }
        IDbSet<ContactAddressCustomer> ContactAddressCustomers { get; set; }
        IDbSet<ContactAddressType> ContactAddressTypes { get; set; }
        IDbSet<ContactAddressUserRole> ContactAddressUserRoles { get; set; }
        IDbSet<CriteriaAssessorAttribute> CriteriaAssessorAttributes { get; set; }
        IDbSet<CriteriaConfig> CriteriaConfigs { get; set; }
        IDbSet<CriteriaOperator> CriteriaOperators { get; set; }
        IDbSet<CriteriaOption> CriteriaOptions { get; set; }
        IDbSet<CriteriaSet> CriteriaSets { get; set; }
        IDbSet<Currency> Currencies { get; set; }
        IDbSet<CurrencyExchangeRate> CurrencyExchangeRates { get; set; }
        IDbSet<Customer> Customers { get; set; }
        IDbSet<CustomerClient> CustomerClients { get; set; }
        IDbSet<CustomerLinkStatu> CustomerLinkStatus { get; set; }
        IDbSet<CustomerUser> CustomerUsers { get; set; }
        IDbSet<DynamicQuestion> DynamicQuestions { get; set; }
        IDbSet<Error> Errors { get; set; }
        IDbSet<ExpenseStatu> ExpenseStatus { get; set; }
        IDbSet<ExpenseType> ExpenseTypes { get; set; }
        IDbSet<ForumAdminReply> ForumAdminReplies { get; set; }
        IDbSet<ForumAssessorReply> ForumAssessorReplies { get; set; }
        IDbSet<ForumCategory> ForumCategories { get; set; }
        IDbSet<ForumReportedReply> ForumReportedReplies { get; set; }
        IDbSet<ForumThread> ForumThreads { get; set; }
        IDbSet<FurtherActionComment> FurtherActionComments { get; set; }
        IDbSet<FurtherNote> FurtherNotes { get; set; }
        IDbSet<Gender> Genders { get; set; }
        IDbSet<GeographicCountry> GeographicCountries { get; set; }
        IDbSet<GeographicCounty> GeographicCounties { get; set; }
        IDbSet<GeographicLocation> GeographicLocations { get; set; }
        IDbSet<GeographicPostalArea> GeographicPostalAreas { get; set; }
        IDbSet<GeographicPostCode> GeographicPostCodes { get; set; }
        IDbSet<GeographicRegion> GeographicRegions { get; set; }
        IDbSet<GeographicWorldArea> GeographicWorldAreas { get; set; }
        IDbSet<Group> Groups { get; set; }
        IDbSet<GroupUser> GroupUsers { get; set; }
        IDbSet<IndustrySector> IndustrySectors { get; set; }
        IDbSet<Log> Logs { get; set; }
        IDbSet<Login> Logins { get; set; }
        IDbSet<Maintenance> Maintenances { get; set; }
        IDbSet<MaintenanceCategory> MaintenanceCategories { get; set; }
        IDbSet<MaintenanceCustomer> MaintenanceCustomers { get; set; }
        IDbSet<ManagementCategory> ManagementCategories { get; set; }
        IDbSet<ManagerArea> ManagerAreas { get; set; }
        IDbSet<ManagerBranch> ManagerBranches { get; set; }
        IDbSet<ManagerBrand> ManagerBrands { get; set; }
        IDbSet<ManagerCallBackRequest> ManagerCallBackRequests { get; set; }
        IDbSet<ManagerClient> ManagerClients { get; set; }
        IDbSet<ManagerClientContactTracking> ManagerClientContactTrackings { get; set; }
        IDbSet<ManagerRegion> ManagerRegions { get; set; }
        IDbSet<ManagerTimeTracker> ManagerTimeTrackers { get; set; }
        IDbSet<Menu> Menus { get; set; }
        IDbSet<MenuConfig> MenuConfigs { get; set; }
        IDbSet<MenuConfigBranch> MenuConfigBranches { get; set; }
        IDbSet<MenuConfigBrand> MenuConfigBrands { get; set; }
        IDbSet<MenuConfigClient> MenuConfigClients { get; set; }
        IDbSet<MenuItem> MenuItems { get; set; }
        IDbSet<MenuItemPossibleAnswer> MenuItemPossibleAnswers { get; set; }
        IDbSet<MenuSection> MenuSections { get; set; }
        IDbSet<MenuSectionPossibleAnswer> MenuSectionPossibleAnswers { get; set; }
        IDbSet<Note> Notes { get; set; }
        IDbSet<NoteCalendar> NoteCalendars { get; set; }
        IDbSet<NoteType> NoteTypes { get; set; }
        IDbSet<Notification> Notifications { get; set; }
        IDbSet<NotificationCategory> NotificationCategories { get; set; }
        IDbSet<PandoraCache> PandoraCaches { get; set; }
        IDbSet<PasswordQuestion> PasswordQuestions { get; set; }
        IDbSet<PasswordReset> PasswordResets { get; set; }
        IDbSet<Period> Periods { get; set; }
        IDbSet<PeriodBrand> PeriodBrands { get; set; }
        IDbSet<PeriodClient> PeriodClients { get; set; }
        IDbSet<Permission> Permissions { get; set; }
        IDbSet<PermissionGroup> PermissionGroups { get; set; }
        IDbSet<PermissionGroupPermission> PermissionGroupPermissions { get; set; }
        IDbSet<PermissionGroupUser> PermissionGroupUsers { get; set; }
        IDbSet<PersonArea> PersonAreas { get; set; }
        IDbSet<PersonBranch> PersonBranches { get; set; }
        IDbSet<PersonBrand> PersonBrands { get; set; }
        IDbSet<PersonCallBackRequest> PersonCallBackRequests { get; set; }
        IDbSet<PersonClient> PersonClients { get; set; }
        IDbSet<PersonClientContactTracking> PersonClientContactTrackings { get; set; }
        IDbSet<PersonRegion> PersonRegions { get; set; }
        IDbSet<PersonTimeTracker> PersonTimeTrackers { get; set; }
        IDbSet<Point> Points { get; set; }
        IDbSet<PointReason> PointReasons { get; set; }
        IDbSet<PossibleAnswer> PossibleAnswers { get; set; }
        IDbSet<Question> Questions { get; set; }
        IDbSet<QuestionDepartment> QuestionDepartments { get; set; }
        IDbSet<Questionnaire> Questionnaires { get; set; }
        IDbSet<QuestionnaireAccountingProduct> QuestionnaireAccountingProducts { get; set; }
        IDbSet<QuestionnaireQuestion> QuestionnaireQuestions { get; set; }
        IDbSet<QuestionnaireQuestionPossibleAnswer> QuestionnaireQuestionPossibleAnswers { get; set; }
        IDbSet<QuestionnaireStatu> QuestionnaireStatus { get; set; }
        IDbSet<QuestionOverwrite> QuestionOverwrites { get; set; }
        IDbSet<QuestionPossibleAnswer> QuestionPossibleAnswers { get; set; }
        IDbSet<QuestionResult> QuestionResults { get; set; }
        IDbSet<QuestionResultAction> QuestionResultActions { get; set; }
        IDbSet<QuestionSection> QuestionSections { get; set; }
        IDbSet<QuestionTag> QuestionTags { get; set; }
        IDbSet<QuestionTracker> QuestionTrackers { get; set; }
        IDbSet<QuestionType> QuestionTypes { get; set; }
        IDbSet<RailStation> RailStations { get; set; }
        IDbSet<Region1> Region1 { get; set; }
        IDbSet<RegionHistory1> RegionHistory1 { get; set; }
        IDbSet<RegionQuestionnaire> RegionQuestionnaires { get; set; }
        IDbSet<RegionStatus1> RegionStatus1 { get; set; }
        IDbSet<RemovalReason> RemovalReasons { get; set; }
        IDbSet<ReportProblemAction> ReportProblemActions { get; set; }
        IDbSet<ReportProblemActionType> ReportProblemActionTypes { get; set; }
        IDbSet<ReportProblemCause> ReportProblemCauses { get; set; }
        IDbSet<ReportProblemTracking> ReportProblemTrackings { get; set; }
        IDbSet<ReportProblemTrackingAction> ReportProblemTrackingActions { get; set; }
        IDbSet<ReportProblemType> ReportProblemTypes { get; set; }
        IDbSet<ResultComment> ResultComments { get; set; }
        IDbSet<Role> Roles { get; set; }
        IDbSet<SimpleVisit> SimpleVisits { get; set; }
        IDbSet<SimpleVisitQuestionResult> SimpleVisitQuestionResults { get; set; }
        IDbSet<SimpleVisitTemplate> SimpleVisitTemplates { get; set; }
        IDbSet<SimpleVisitTemplateBranch> SimpleVisitTemplateBranches { get; set; }
        IDbSet<SQQOPossibleAnswer> SQQOPossibleAnswers { get; set; }
        IDbSet<StaffAge> StaffAges { get; set; }
        IDbSet<StaffClothingColour> StaffClothingColours { get; set; }
        IDbSet<StaffClothingItem> StaffClothingItems { get; set; }
        IDbSet<StaffFeature> StaffFeatures { get; set; }
        IDbSet<StaffHairColour> StaffHairColours { get; set; }
        IDbSet<StaffHairLength> StaffHairLengths { get; set; }
        IDbSet<StaffHairStyle> StaffHairStyles { get; set; }
        IDbSet<StaffHeight> StaffHeights { get; set; }
        IDbSet<StaffMember> StaffMembers { get; set; }
        IDbSet<StaffMemberClothingItem> StaffMemberClothingItems { get; set; }
        IDbSet<StaffMemberFeature> StaffMemberFeatures { get; set; }
        IDbSet<SubDynamicQuestion> SubDynamicQuestions { get; set; }
        IDbSet<SubQuestionnaire> SubQuestionnaires { get; set; }
        IDbSet<SubQuestionnaireQuestionOverwrite> SubQuestionnaireQuestionOverwrites { get; set; }
        IDbSet<Suggestion> Suggestions { get; set; }
        IDbSet<SuggestionStatu> SuggestionStatus { get; set; }
        IDbSet<SuggestionVote> SuggestionVotes { get; set; }
        IDbSet<sysdiagram> sysdiagrams { get; set; }
        IDbSet<Tag> Tags { get; set; }
        IDbSet<TelephoneRecording> TelephoneRecordings { get; set; }
        IDbSet<Terminology> Terminologies { get; set; }
        IDbSet<TerminologyBrand> TerminologyBrands { get; set; }
        IDbSet<TerminologyClient> TerminologyClients { get; set; }
        IDbSet<TimeTracker> TimeTrackers { get; set; }
        IDbSet<TimeTrackerType> TimeTrackerTypes { get; set; }
        IDbSet<Tour> Tours { get; set; }
        IDbSet<TourStep> TourSteps { get; set; }
        IDbSet<TourStepPlacement> TourStepPlacements { get; set; }
        IDbSet<TourUserRole> TourUserRoles { get; set; }
        IDbSet<TourUserRoleTourStep> TourUserRoleTourSteps { get; set; }
        IDbSet<TradeLevel> TradeLevels { get; set; }
        IDbSet<User> Users { get; set; }
        IDbSet<UserImpersonationUserRole> UserImpersonationUserRoles { get; set; }
        IDbSet<UserRole> UserRoles { get; set; }
        IDbSet<Visit> Visits { get; set; }
        IDbSet<VisitAction> VisitActions { get; set; }
        IDbSet<VisitAssessor> VisitAssessors { get; set; }
        IDbSet<VisitCallBackRequest> VisitCallBackRequests { get; set; }
        IDbSet<VisitCallInLog> VisitCallInLogs { get; set; }
        IDbSet<VisitDetail> VisitDetails { get; set; }
        IDbSet<VisitNote> VisitNotes { get; set; }
        IDbSet<VisitPoint> VisitPoints { get; set; }
        IDbSet<VisitStatu> VisitStatus { get; set; }
        IDbSet<VisitStatusHistory> VisitStatusHistories { get; set; }
        IDbSet<VisitTimeTracker> VisitTimeTrackers { get; set; }
        IDbSet<VisitType> VisitTypes { get; set; }
        IDbSet<VisitTypeExpenseType> VisitTypeExpenseTypes { get; set; }
        IDbSet<Weather> Weathers { get; set; }
        IDbSet<Article> Articles { get; set; }
        IDbSet<ArticlePermission> ArticlePermissions { get; set; }
        IDbSet<Page> Pages { get; set; }
        IDbSet<PageArticle> PageArticles { get; set; }
        IDbSet<PageTour> PageTours { get; set; }
        IDbSet<AreaLegacyUser> AreaLegacyUsers { get; set; }
        IDbSet<BranchLegacyUser> BranchLegacyUsers { get; set; }
        IDbSet<BrandLegacyUser> BrandLegacyUsers { get; set; }
        IDbSet<ClientLegacyUser> ClientLegacyUsers { get; set; }
        IDbSet<RegionLegacyUser> RegionLegacyUsers { get; set; }
        IDbSet<Messages_0> Messages_0 { get; set; }
        IDbSet<Messages_0_Id> Messages_0_Id { get; set; }
        IDbSet<Schema> Schemata { get; set; }
        IDbSet<BranchSocialNetwork> BranchSocialNetworks { get; set; }
        IDbSet<BrandSocialNetwork> BrandSocialNetworks { get; set; }
        IDbSet<ClientSocialNetwork> ClientSocialNetworks { get; set; }
        IDbSet<SocialNetwork> SocialNetworks { get; set; }
    }
}